### ISSUE TITLE
Cannot keep the menu height when working with Bootstrap

### ISSUE THREAD

**Issue by yckelvin** [pagerange/prmenu#2]
$('#top-menu').prmenu({
    "height": "50"
});

When working with Bootstrap 3.3.6 together, only the mobile view can keep the menu item height at 50px.

**Comment by pagerange** [comment]
I can confirm that is happening.  I have added a fix in the latest commit.  This corrects the problem on my test pages using Bootstrap.  Let me know if the problem continues.

**Comment by yckelvin** [comment]
Yes, the problem fixed after replacing the script with new version.  Thanks a lot!
